### ISSUE TITLE
Version not up to date

### ISSUE THREAD

**Issue by nerohmot** [conda-forge/bitarray-feedstock#49]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue: bitarry has new versions on PyPI, however they don't propagate automatically to conda-forge ...

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by nehaljwani** [comment]
Fixed via https://github.com/conda-forge/bitarray-feedstock/pull/50

**Comment by nerohmot** [comment]
:pray:
