### ISSUE TITLE
Test Failures in s390x

### ISSUE THREAD

**Issue by varlackc** [conda-forge/bitarray-feedstock#61]
- [ x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:
`bitarray` test fails for `linux-s390x` due to a big/little-endian issue 
<br/>
Environment (<code>conda list</code>):
`linux-s390x`
<details>

Details:

There seems to be an issue during the test on `bitarray` for `linux-s390x` 
The issue seems to be a big/little-endian issue in the testsuite of bitarray

Here is the error:
--
FAILED (failures=24, errors=1)

Traceback (most recent call last):

  File "/opt/conda/conda-bld/bitarray_1639775601698/test_tmp/run_test.py", line 7, in <module>

    assert bitarray.test().wasSuccessful()

AssertionError

Tests failed for bitarray-2.3.4-py37h2a837d6_1.tar.bz2 - moving package to /opt/conda/conda-bld/broken
--

**Comment by nehaljwani** [comment]
Closing, as this has already been reported upstream https://github.com/ilanschnell/bitarray/issues/159

**Comment by ilanschnell** [comment]
This problem now fixed upstream in bitarray 2.3.5
